export enum CONTEST_STATUS {
  PENDING = "PENDING",
  NOW = "NOW",
  BEFORE = "BEFORE",
  FINISHED = "FINISHED"
}

export enum PROJECT_STATUS {
  PENDING = "PENDING",
  APPROVAL = "APPROVAL",
  REJECTED = "REJECTED",
  MODIFICATION = "MODIFICATION",
  DELETION = "DELETION",
}
